version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: an3rd
      POSTGRES_USER: apiuser
      POSTGRES_PASSWORD: E@!VT8I*#btgd5Pd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
